### ISSUE TITLE
[armhf] Freeze buster backports kernel until at least 5.10.17

### ISSUE THREAD

**Issue by abalmos** [oats-center/isoblue-avena#129]
**Freeze kernel updates until 5.10.17 lands and is tested.**

Currently the backports kernel is 5.10.13. This kernel panics on boot. We believe [this](https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/commit/?h=v5.10.23&id=249735b011234a65a720952d5451156be8baa50f) patch is the fix, which landed in 5.10.17.

**Comment by abalmos** [comment]
5.10.17 landed in backports. Needs testing.

**Comment by facastiblancor** [comment]
Closing as 5.10.17 indeed fixed the panic.
