### ISSUE TITLE
Support for RFC 1149 & RFC 2549

### ISSUE THREAD

**Issue by aaron97neu** [oats-center/isoblue-avena#135]
https://tools.ietf.org/html/rfc1149
https://tools.ietf.org/html/rfc6214

Among others, the NATS python bindings support IPOAC. We should move to support this functionality to ensure support of all NATS transport protocols. As noted [here](https://en.wikipedia.org/wiki/IP_over_Avian_Carriers#Other_avian_data_transfer_methods) there have been multiple examples where this transport protocol has proven to have a significantly higher throughput than traditional TCP/IP, specifically in rural situations. This may require some modifications to the physical ISOBlue device but I feel there are some opportunities, especially during planting and harvest, for interoperability of the grain and seed tanks on the machines and the avian maintenance module on ISOBlue Avena

Depending on implementation, this functionality may also be able to give Purdue CS182 students a physical demonstration of the pigeonhole principle further giving proof that ISOBlue Avena brings the agricultural and technological sectors together in an educational context

**Comment by abalmos** [comment]
You got me to read the entire issue!
