### ISSUE TITLE
Refactor docker-compose.yml

### ISSUE THREAD

**Issue by wang701** [oats-center/isoblue-avena#23]
Current `docker-compose.yml` and `.env` is very platform-specific. We should come up with a way to improve this.

**Comment by abalmos** [comment]
Maybe we should make a script that just something like:

`docker-compose -f docker-compose.db.yml -f docker-compose.can.yml ... up`

Where the `docker-compose.*.yml` files are everything in a folder somewhere. Like how many of the Debian `.d` folders work.

Then our roles can just drop the compose file they need into the folder to get their stuff running. 

Maybe even call this an "avena" systemd service ... so something like:

`systemctl start avena` would call `docker-compose -f .. -f .. up -d`
`systemctl stop avena` would call `docker-compose -f .. -f .. down`
`systemctl restart avena` would call `docker-compose -f .. -f .. restart`
etc.

I wonder if such a thing already exists?

Bonus idea: It could be something like: `systemctl start avena@/home/joe-shmoe/avena` to allow individual users to have their own docker services ... Maybe this is a security issue? Can some one, some how use this to elevate to root or access another user's containers? ... This whole use case is not that important to us right now.

@facastiblancor @wang701 @aaron97neu

**Comment by abalmos** [comment]
Open question: When removing a compose file from the folder, how do we ensure the associated containers are stopped and cleaned up?

**Comment by wang701** [comment]
@abalmos 

I did a quick search how people are handling this. It turns out that people do use `systemd` to control which `docker-compose.yml` to use.

See [this](https://gist.github.com/mosquito/b23e1c1e5723a7fd9e6568e5cf91180f) and [this](https://community.hetzner.com/tutorials/docker-compose-as-systemd-service).

These solutions are similar to your ideas of `systemctl start avena@/home/joe-shmoe/avena` but they replace the path with a template path `/etc/docker/%i`. And I think it is safer this way.

**Comment by abalmos** [comment]
This seems outdated now.
