### ISSUE TITLE
What containers to build and when? 

### ISSUE THREAD

**Issue by abalmos** [oats-center/isoblue-avena#31]
What containers to build and based on what?

# When to build
## Current
- All containers are built on all pushes
- All containers are built on all PRs

NB: No need to deal with GH action rules

## Option 1
- All containers are built on every push that touches a file in `services/*`
- All containers are built with an PR that touches a file in `services/*`

NB: This requires only one GH workflow file (and only one line needs to be added to enable a new service). DockerHub "does the right thing" when you push the exactly same container to it multiple times.

## Option 2
- Container is only built on pushes that touch a file in `services/<service-name/*`
- Container is only build if PR touches a file is under `services/<service-name/*`

NB: This is more "correct" but would need a workflow for each service (I think) and those work flows would largely be exact duplicates of each other. However, this enables services that need a non-standard workflow. We could factor a lot of our custom logic into a bash file that all workflows call.

# When to push
## Current
- All built containers are pushed to DockerHub (`isoblue`) right away.

# Option 1 
- Push all "release" containers (push to `master`, `v*` branches, and/or `v*` tags) to DockerHub `isoblue right away.
- Push all "non-release" containers to DockerHub `isobluedev` right away for easier PR / branch testing

# Option 2
- Push all "release" containers to DockerHub `isoblue` right away
- Push all "non-release" containers to a private Docker server for easier PR / branch testing

# Option 3
- Only push "release" containers to DockerHub `isoblue`

**Comment by abalmos** [comment]
Something else to consider: Github can also host Docker images (https://github.com/OATS-Group/isoblue-avena/packages)

**Comment by facastiblancor** [comment]
I think  _on, heartbeat and cell-logger_ are good candidates. For the first two, the code is easy to build as a container, however, with _cell-logger_ we need to do some changes for it to poll ModemManager's data using dbus.

**When to build?** 
I think option 1 would simplify our workflow and save us future problems with workflow and duplicated stuff.
**When to push?** 
Option 2 for simplicity and better testing posibilities.

**Comment by abalmos** [comment]
We have a GHA solution now
