### ISSUE TITLE
Bring Prometheus/Grafana back 

### ISSUE THREAD

**Issue by abalmos** [oats-center/isoblue-avena#65]
Restore the Prometheus/Grafana dashboard functionality. It was lost during move to oats2 and new docker-compose strategy.

**Comment by aaron97neu** [comment]
@abalmos What still needs to be done to close this issue/

**Comment by abalmos** [comment]
Nothing. This work requires no PRs to `isoblue-avena`. One day, we should have some example compose files for `container-maintainer` and then we could include `node-exporter`, `cadvisor`, etc.

Setting up prometheus is not dependent on Avena. We could show some example configs and a dashboards though?
