### ISSUE TITLE
Containerized CAN to timescale

### ISSUE THREAD

**Issue by abalmos** [oats-center/isoblue-avena#66]
A canbus to postgres container.

A few ideas:
1. host networking mode and a simple python script to read from SocketCAN in chunks and write to timescale
2. socketcand (on host or in host mode container?) + a python container to read from socketcand and write to timescale
3. can-to-nanomsg (on host or in host mode container?) + a python container to read from nanomsg and write to timescale

Option 3 has the advantage of letting us try out nano message where we thought DBUS might work well for us. 
Option 2 has the advantage of using existing socketcan code
Option 1 has the advantage of less moving parts.

Current thinking: Try out option 3 as a learning experience around nanomsg. Most of the core code is needed for all options, so we can always "downgrade" if we experience issues.

Current thinking 2: We can keep running our `candump` loggers a for a while too ... as a backup until we trust our new setup.

**Comment by facastiblancor** [comment]
I like the idea of trying new things. However, I checked the nanomsg website and found it was superseded by NNG. I read both sites and seems there is no big difference between them. From what I understood, NNG is written and implemented in C, which I _hope_ won't give much trouble when porting software between ARM and x86.

**Comment by aaron97neu** [comment]
Should this be closed with the merged of #84?

**Comment by facastiblancor** [comment]
Agree. This was addressed in #84, but I think we should open a new issue to keep track of our upgrade to nanomsg in future releases.
