### ISSUE TITLE
oada_upload postgres select query slow

### ISSUE THREAD

**Issue by abalmos** [oats-center/isoblue-avena#69]
Might need to make an index on (sent, timestamp) or something. Or maybe use `sent` as the space index in TSDB.

**Comment by aaron97neu** [comment]
Adding a index on the `gps_sent` table on dev05 `(sent, g_time DESC)` cased this change in container CPU usage. Will implement and make PR soon
![image](https://user-images.githubusercontent.com/13039768/94466117-eb52fb80-018e-11eb-95ab-44dcca2c93a8.png)
