### ISSUE TITLE
container-maintainer causes outages

### ISSUE THREAD

**Issue by abalmos** [oats-center/isoblue-avena#74]
Currently a service that needs updated is stopped, downloaded, started. Over cell downloaded can take a while. It will be nice to pull the images before we do the restart so that the "downloaded" part is fast, limiting the service outage.

**Comment by aaron97neu** [comment]
Doing a `docker-compose pull` before stopping the containers many be the move. However, I am unsure if there are side effects of pulling an already running container.

**Comment by aaron97neu** [comment]
Per 9/21 discussion:
container-maintainer should do the following:
```
docker-compose pull   # Get new images, even if they are the same tag
docker-compose up -d  # Automatically restart new images, leave those that are fine
docker system prune   # Remove and clean up
```

The issue with this is it will not stop containers that were removed from the `docker-compose.yml`. This is require a diff between the old and new docker-compose files to determine what containers should be stopped

**Comment by aaron97neu** [comment]
Per 9/28 discussion this is complete, moving `docker system prune` to a new issue not due with `0.1.0`
