### ISSUE TITLE
0.2.0 Inter-Container Data Bus Release Plan

### ISSUE THREAD

**Issue by aaron97neu** [oats-center/isoblue-avena#90]
Github's milestone description does not allow for anything more than a paragraph without an formatting. A issue provides a better place to list and discuss the features planned for a milestone

Once the 0.2.0 milestone is reached, this issue will be closed and 0.2.0 will be considered released

In 0.2.0 we will be focusing on integrating a common bus that all containers can use to exchange data. An example of this would be a privileged CAN container running in host mode can read an publish can data so that other containers can be run in a safer non-host mode and not worry about the details and complications of reading from CAN

Things we have tried
- Kafka: too heavy, overpowered for out needs
- DBUS: no good python lib support, does not handle a high rate of small messages well

Current direction: Nanomsg or mqtt. Will try nanomsg and if we run into significant issues, will pivot to mqtt

**Comment by abalmos** [comment]
We have converged on NATS. Service upgrades in progress.
